# Generated by Django 4.0.6 on 2022-07-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_authors_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(db_index=True, default='eng', max_length=20, unique=True),
        ),
    ]
