# Generated by Django 4.0.6 on 2022-07-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_books_author_books_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(blank=True, to='inventory.authors'),
        ),
    ]
