# Generated by Django 4.0.6 on 2022-07-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_books_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='authors', to='inventory.authors'),
        ),
    ]
